import logging
from typing import Dict, Any, List

from .react_generator import ReactGenerator
from .fastapi_generator import FastAPIGenerator

logger = logging.getLogger("aether.generators.code_generator")


class CodeGenerator:
    """
    Converts an AI blueprint into project files.
    """

    def __init__(self):
        self.react_generator = ReactGenerator()
        self.fastapi_generator = FastAPIGenerator()

    def generate(self, blueprint: Dict[str, Any]) -> List[Dict[str, str]]:
        """
        Returns a list of starter project files from the blueprint.
        """
        logger.info("Starting combined project files generation.")
        
        summary = blueprint.get("Executive Summary", "AI Project")
        architecture = blueprint.get("System Architecture", "A generated project")

        # 1. Root README.md
        files = [
            {
                "path": "README.md",
                "content": (
                    f"# {summary}\n\n"
                    "This project was generated by AETHER from a blueprint.\n\n"
                    f"## Overview\n{architecture}\n"
                ),
            }
        ]

        # 2. Generate FastAPI backend files
        try:
            backend_files = self.fastapi_generator.generate(blueprint)
            files.extend(backend_files)
        except Exception as exc:
            logger.error("Error generating backend files: %s", exc, exc_info=True)

        # 3. Generate React frontend files and prefix with "frontend/"
        try:
            frontend_files = self.react_generator.generate(blueprint)
            for f in frontend_files:
                # Ensure the path starts with frontend/
                path = f["path"]
                f["path"] = f"frontend/{path}"
                files.append(f)
        except Exception as exc:
            logger.error("Error generating frontend files: %s", exc, exc_info=True)

        logger.info("Generated %s total files for project generation", len(files))
        return files